name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  export DEBIAN_FRONTEND="noninteractive" && sudo apt-get update -y && sudo apt-get install -y gcc-arm-none-eabi libclang-dev && rustup target add thumbv7em-none-eabihf && cargo build --verbose
